# max number of events to store / retain in memory
max_events = 5

# file to execute (if set) when a new event is seen
exec_program = "./new-event"

# log level (given to the env_logger crate)
# accepted values: off, error, warn, info, debug, trace
log_level = "trace"

[persist]
# this file (if set) will be read upon start-up, and written to whenever new events are received
file = "events.json"

[http_server]
listen = "localhost:3000"

# you probably don't need to change these
[internal]
tokio_broadcast_channel_size = 16
